services:
  authorization:
    build: ./
    container_name: authorization
    ports:
      - ${REST_PORT}:${REST_PORT}
      - ${GRPC_PORT}:${GRPC_PORT}
    env_file:
      - ./.env

  storage:
    image: postgres:16-alpine
    container_name: authorization_storage_pq
    restart: always
    environment:
      POSTGRES_USER: rename
      POSTGRES_PASSWORD: rename
      POSTGRES_DB: rename
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: